stages:
  - build
  - package
  - deploy-dev
  - deploy-prd

variables:
  SERVICE_NAME: iadp-front-web

build:
  image: $REGISTRY_ADDRESS/devops/nodejs/build
  stage: build
  only:
    - tags
    - master
    - develop
  script:
    - yarn config get registry && yarn && yarn lint && yarn build
  artifacts:
    paths:
      - dist
      - Dockerfile
    expire_in: 2 hrs
  tags:
    - nodejs

package:
  image: $REGISTRY_ADDRESS/devops/docker/package
  stage: package
  variables:
    GIT_STRATEGY: none
  only:
    - tags
    - master
    - develop
  script:
    - package
  tags:
    - docker

deploy-dev:
  image: $REGISTRY_ADDRESS/devops/docker/deploy
  stage: deploy-dev
  variables:
    GIT_STRATEGY: none
  dependencies: []
  only:
    - master
    - develop
  except:
    - tags
  script:
    - deploy -service $SERVICE_NAME
  environment: aiads-dev
  tags:
    - docker

deploy-prd:
  image: $REGISTRY_ADDRESS/devops/docker/deploy
  stage: deploy-prd
  variables:
    GIT_STRATEGY: none
  dependencies: []
  only:
    - tags
    - master
  except:
    - branches
  script:
    - deploy -service $SERVICE_NAME -template web -vars port=8005
  environment: aiads-prd
  tags:
    - docker
  when: manual

