stages:
  - lint
  - build
  - package
  - deploy

variables:
  SERVICE_NAME: iadp-front-web-demo
  YARN_REGISTRY: https://registry.yarnpkg.com

lint:
  image: $REGISTRY_ADDRESS/devops/nodejs/build
  stage: lint
  script:
    - yarn config set registry $YARN_REGISTRY && yarn && yarn lint
  only:
    - demo
  tags:
    - nodejs

build:
  image: $REGISTRY_ADDRESS/devops/nodejs/build
  stage: build
  only:
    - demo
  script:
    - yarn config set registry $YARN_REGISTRY && yarn && yarn build
  artifacts:
    paths:
      - dist
      - Dockerfile
    expire_in: 2 hrs
  tags:
    - nodejs

package:
  image: $REGISTRY_ADDRESS/devops/docker/package
  stage: package
  variables:
    GIT_STRATEGY: none
  only:
    - demo
  script:
    - package
  tags:
    - docker

deploy:
  image: $REGISTRY_ADDRESS/devops/docker/deploy
  stage: deploy
  variables:
    GIT_STRATEGY: none
  dependencies: []
  only:
    - demo
  script:
    - deploy -service $SERVICE_NAME
  environment: aiads-dev
  tags:
    - docker

